# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - stg-ntest-1-wapp(Production), Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: stgcdrxacr1.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3D1B69BA5639410884A1CBD9FB8533DB }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_A4B162F2C9874D6B9FA567791D3991F0 }}

    - run: |
        docker build . -t stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3D1B69BA5639410884A1CBD9FB8533DB }}/stg-ntest-1-wapp-image:${{ github.sha }}
        docker push stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3D1B69BA5639410884A1CBD9FB8533DB }}/stg-ntest-1-wapp-image:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: stg-ntest-1-wapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D1818F4AD824F51A05CCF2FC50F4B30 }}
        images: stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3D1B69BA5639410884A1CBD9FB8533DB }}/stg-ntest-1-wapp-image:${{ github.sha }}

