# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - stg-ntest-1-wapp(Production), Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: stgcdrxacr1.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_65B95DBA4DDA422EBEFB94959B26C234 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_D28B8B7A2F794A11901234C5CEB5C28B }}

    - run: |
        docker build . -t stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_65B95DBA4DDA422EBEFB94959B26C234 }}/stg-ntest-1-wapp-image:${{ github.sha }}
        docker push stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_65B95DBA4DDA422EBEFB94959B26C234 }}/stg-ntest-1-wapp-image:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: stg-ntest-1-wapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_84311BCBC10244B58419D9AD1FD5B936 }}
        images: stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_65B95DBA4DDA422EBEFB94959B26C234 }}/stg-ntest-1-wapp-image:${{ github.sha }}

