# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - prd-ntest-wapp(Production), Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: prdntestacr.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E81EDC3E1D9741BF981D3A52C231E4A1 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_C54A9433490A473F8AE75D29A78DB307 }}

    - run: |
        docker build . -t prdntestacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E81EDC3E1D9741BF981D3A52C231E4A1 }}/ntestimage:${{ github.sha }}
        docker push prdntestacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E81EDC3E1D9741BF981D3A52C231E4A1 }}/ntestimage:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: prd-ntest-wapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FAE227D5BD404181878A7D09ABF9A5CC }}
        images: prdntestacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E81EDC3E1D9741BF981D3A52C231E4A1 }}/ntestimage:${{ github.sha }}

